I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 36, in script call
    call SC_DEV from _call_SC_DEV
  File "game/script.rpy", line 36, in script call
    call SC_DEV from _call_SC_DEV
ScriptError: could not find label 'SC_DEV'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 36, in script call
    call SC_DEV from _call_SC_DEV
  File "/home/xubuntu/Desktop/renpy-8.3.7-sdk/renpy/ast.py", line 1427, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 36, in script call
    call SC_DEV from _call_SC_DEV
  File "/home/xubuntu/Desktop/renpy-8.3.7-sdk/renpy/script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'SC_DEV'.

Linux-6.11.0-17-generic-x86_64-with-glibc2.39 x86_64
Ren'Py 8.3.7.25031702
FrankOfTheAbyss 1.0
Sat Apr 12 11:18:44 2025
